/**
 * Roadmap Types - Backend
 * 
 * Tipos compartidos para el sistema de roadmap que agrega todos los eventos
 * de la aplicación (shows, viajes, finanzas, tareas) en una vista unificada
 */

export interface RoadmapNode {
  id: string;
  type: 'show' | 'travel' | 'finance' | 'task' | 'release' | 'milestone';
  title: string;
  description?: string;
  startDate: string; // ISO date string
  endDate?: string;  // Para eventos con duración
  status: 'confirmed' | 'pending' | 'cancelled' | 'completed' | 'draft';
  priority: 'low' | 'medium' | 'high' | 'critical';
  assignedTo?: string[]; // User IDs
  location?: {
    city?: string;
    venue?: string;
    coordinates?: [number, number]; // [lat, lng]
  };
  
  // Metadata específica por tipo
  metadata: {
    // Show metadata
    showId?: string;
    ticketsSold?: number;
    capacity?: number;
    fee?: number;
    
    // Travel metadata  
    flightId?: string;
    hotelId?: string;
    transportType?: 'flight' | 'train' | 'car' | 'bus';
    cost?: number;
    
    // Finance metadata
    transactionId?: string;
    amount?: number;
    category?: string;
    dueDate?: string;
    
    // Task metadata
    taskId?: string;
    progress?: number; // 0-100
    estimatedHours?: number;
    
    // Release/Milestone metadata
    version?: string;
    deliverables?: string[];
  };
}

export interface Dependency {
  id: string;
  fromNodeId: string;
  toNodeId: string;
  type: 'finish_to_start' | 'start_to_start' | 'finish_to_finish' | 'start_to_finish';
  lag?: number; // Days offset
  description?: string;
  isAutoGenerated: boolean; // true if created by intelligent connection
}

export interface RoadmapResponse {
  nodes: RoadmapNode[];
  dependencies: Dependency[];
  metadata: {
    totalEvents: number;
    dateRange: {
      start: string;
      end: string;
    };
    lastUpdated: string;
    generatedAt: string;
  };
}

// Request params for roadmap API
export interface RoadmapRequest {
  startDate?: string;
  endDate?: string;
  types?: ('show' | 'travel' | 'finance' | 'task' | 'release' | 'milestone')[];
  assignedTo?: string[];
  status?: ('confirmed' | 'pending' | 'cancelled' | 'completed' | 'draft')[];
  priority?: ('low' | 'medium' | 'high' | 'critical')[];
}

// Internal service interfaces
export interface ShowData {
  id: string;
  date: string;
  venue: string;
  city: string;
  status: string;
  fee: number;
  capacity?: number;
  ticketsSold?: number;
}

export interface TravelData {
  id: string;
  type: 'flight' | 'hotel' | 'transport';
  fromDate: string;
  toDate?: string;
  fromLocation: string;
  toLocation?: string;
  cost: number;
  status: string;
  relatedShowId?: string;
}

export interface FinanceData {
  id: string;
  type: 'income' | 'expense' | 'invoice' | 'payment';
  amount: number;
  category: string;
  dueDate: string;
  status: string;
  relatedShowId?: string;
  description: string;
}

export interface TaskData {
  id: string;
  title: string;
  description: string;
  assignedTo: string[];
  dueDate: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'todo' | 'in_progress' | 'completed';
  progress: number;
  estimatedHours?: number;
  relatedShowId?: string;
}

// Auto-dependency generation rules
export interface DependencyRule {
  fromType: RoadmapNode['type'];
  toType: RoadmapNode['type'];
  relationship: Dependency['type'];
  condition: (fromNode: RoadmapNode, toNode: RoadmapNode) => boolean;
  lag?: number;
  description: string;
}