/**
 * Roadmap Types - Frontend
 * 
 * Tipos compartidos entre backend y frontend para el sistema de roadmap
 */

export interface RoadmapNode {
  id: string;
  type: 'show' | 'travel' | 'finance' | 'task' | 'release' | 'milestone';
  title: string;
  description?: string;
  startDate: string; // ISO date string
  endDate?: string;  // Para eventos con duración
  status: 'confirmed' | 'pending' | 'cancelled' | 'completed' | 'draft';
  priority: 'low' | 'medium' | 'high' | 'critical';
  assignedTo?: string[]; // User IDs
  location?: {
    city?: string;
    venue?: string;
    coordinates?: [number, number]; // [lat, lng]
  };
  
  // Metadata específica por tipo
  metadata: {
    // Show metadata
    showId?: string;
    ticketsSold?: number;
    capacity?: number;
    fee?: number;
    
    // Travel metadata  
    flightId?: string;
    hotelId?: string;
    transportType?: 'flight' | 'train' | 'car' | 'bus';
    cost?: number;
    location?: string;
    
    // Finance metadata
    transactionId?: string;
    amount?: number;
    category?: string;
    dueDate?: string;
    
    // Task metadata
    taskId?: string;
    progress?: number; // 0-100
    estimatedHours?: number;
    status?: 'pending' | 'in-progress' | 'completed' | 'cancelled';
    
    // Release/Milestone metadata
    version?: string;
    deliverables?: string[];
  };
}

export interface Dependency {
  id: string;
  fromNodeId: string;
  toNodeId: string;
  type: 'finish_to_start' | 'start_to_start' | 'finish_to_finish' | 'start_to_finish';
  lag?: number; // Days offset
  description?: string;
  isAutoGenerated: boolean; // true if created by intelligent connection
}

export interface RoadmapResponse {
  nodes: RoadmapNode[];
  dependencies: Dependency[];
  users?: UserInfo[];
  metadata: {
    totalEvents: number;
    dateRange: {
      start: string;
      end: string;
    };
    lastUpdated: string;
    generatedAt: string;
  };
}

export interface RoadmapRequest {
  startDate?: string;
  endDate?: string;
  types?: RoadmapNode['type'][];
  assignedTo?: string[];
  status?: RoadmapNode['status'][];
  priority?: RoadmapNode['priority'][];
}

// Frontend-specific types
export interface RoadmapFilters {
  assignedTo: string[] | null;
  types: RoadmapNode['type'][] | null;
  status: RoadmapNode['status'][] | null;
  priority: RoadmapNode['priority'][] | null;
  dateRange: {
    start: string | null;
    end: string | null;
  };
  searchQuery: string;
}

export interface SimulationState {
  isActive: boolean;
  modifiedNodes: RoadmapNode[];
  originalNodes: RoadmapNode[];
  financialImpact: FinancialImpact | null;
  simulationId: string | null;
}

export interface FinancialImpact {
  totalCostChange: number;
  affectedNodes: number;
  impactLevel: 'low' | 'medium' | 'high';
  calculationTime: number;
  affectedTransactions?: number;
  newEstimatedProfit?: number;
  riskFactors?: string[];
  breakdown?: {
    travelCosts: number;
    venueCosts: number;
    opportunityCost: number;
  };
}

export interface RoadmapViewConfig {
  viewType: 'gantt' | 'timeline' | 'calendar';
  zoom: 'day' | 'week' | 'month' | 'quarter';
  showDependencies: boolean;
  showCriticalPath: boolean;
  groupBy: 'none' | 'type' | 'assignee' | 'priority';
}

// Action types for store
export type RoadmapAction =
  | { type: 'SET_LOADING'; payload: boolean }
  | { type: 'SET_NODES'; payload: RoadmapNode[] }
  | { type: 'SET_DEPENDENCIES'; payload: Dependency[] }
  | { type: 'SET_FILTERS'; payload: Partial<RoadmapFilters> }
  | { type: 'SET_ERROR'; payload: string | null }
  | { type: 'START_SIMULATION'; payload: RoadmapNode[] }
  | { type: 'UPDATE_SIMULATION_NODE'; payload: { nodeId: string; changes: Partial<RoadmapNode> } }
  | { type: 'END_SIMULATION' }
  | { type: 'SET_FINANCIAL_IMPACT'; payload: FinancialImpact }
  | { type: 'SET_VIEW_CONFIG'; payload: Partial<RoadmapViewConfig> };

// User data for filters
export interface UserInfo {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  role?: string;
}

export interface GanttTask {
  id: string;
  title: string;
  start: Date;
  end: Date;
  type: RoadmapNode['type'];
  priority: RoadmapNode['priority'];
  assignedTo?: string;
  progress: number;
  dependencies: string[];
  cost: number;
  location?: string;
  status: 'pending' | 'in-progress' | 'completed' | 'cancelled';
}

export interface TimelineRange {
  start: Date;
  end: Date;
  role: string;
}