// Full ISO 3166-1 alpha-2 list (independent + some assigned territories) with English & Spanish exonyms.
// NOTE: Spanish names follow common usage (ONU / Wikipedia ES). Some territories intentionally included for touring relevance.
// If future localization nuances arise, adjust entries here (avoid duplicating elsewhere).
interface CountryEntry { code: string; en: string; es: string }

const COUNTRY_LIST: CountryEntry[] = [
  { code: 'AF', en: 'Afghanistan', es: 'Afganistán' },
  { code: 'AX', en: 'Åland Islands', es: 'Islas Åland' },
  { code: 'AL', en: 'Albania', es: 'Albania' },
  { code: 'DZ', en: 'Algeria', es: 'Argelia' },
  { code: 'AS', en: 'American Samoa', es: 'Samoa Americana' },
  { code: 'AD', en: 'Andorra', es: 'Andorra' },
  { code: 'AO', en: 'Angola', es: 'Angola' },
  { code: 'AI', en: 'Anguilla', es: 'Anguila' },
  { code: 'AQ', en: 'Antarctica', es: 'Antártida' },
  { code: 'AG', en: 'Antigua and Barbuda', es: 'Antigua y Barbuda' },
  { code: 'AR', en: 'Argentina', es: 'Argentina' },
  { code: 'AM', en: 'Armenia', es: 'Armenia' },
  { code: 'AW', en: 'Aruba', es: 'Aruba' },
  { code: 'AU', en: 'Australia', es: 'Australia' },
  { code: 'AT', en: 'Austria', es: 'Austria' },
  { code: 'AZ', en: 'Azerbaijan', es: 'Azerbaiyán' },
  { code: 'BS', en: 'Bahamas', es: 'Bahamas' },
  { code: 'BH', en: 'Bahrain', es: 'Baréin' },
  { code: 'BD', en: 'Bangladesh', es: 'Bangladés' },
  { code: 'BB', en: 'Barbados', es: 'Barbados' },
  { code: 'BY', en: 'Belarus', es: 'Bielorrusia' },
  { code: 'BE', en: 'Belgium', es: 'Bélgica' },
  { code: 'BZ', en: 'Belize', es: 'Belice' },
  { code: 'BJ', en: 'Benin', es: 'Benín' },
  { code: 'BM', en: 'Bermuda', es: 'Bermudas' },
  { code: 'BT', en: 'Bhutan', es: 'Bután' },
  { code: 'BO', en: 'Bolivia', es: 'Bolivia' },
  { code: 'BQ', en: 'Bonaire, Sint Eustatius and Saba', es: 'Caribe Neerlandés' },
  { code: 'BA', en: 'Bosnia and Herzegovina', es: 'Bosnia y Herzegovina' },
  { code: 'BW', en: 'Botswana', es: 'Botsuana' },
  { code: 'BV', en: 'Bouvet Island', es: 'Isla Bouvet' },
  { code: 'BR', en: 'Brazil', es: 'Brasil' },
  { code: 'IO', en: 'British Indian Ocean Territory', es: 'Territorio Británico del Océano Índico' },
  { code: 'BN', en: 'Brunei Darussalam', es: 'Brunéi' },
  { code: 'BG', en: 'Bulgaria', es: 'Bulgaria' },
  { code: 'BF', en: 'Burkina Faso', es: 'Burkina Faso' },
  { code: 'BI', en: 'Burundi', es: 'Burundi' },
  { code: 'CV', en: 'Cabo Verde', es: 'Cabo Verde' },
  { code: 'KH', en: 'Cambodia', es: 'Camboya' },
  { code: 'CM', en: 'Cameroon', es: 'Camerún' },
  { code: 'CA', en: 'Canada', es: 'Canadá' },
  { code: 'KY', en: 'Cayman Islands', es: 'Islas Caimán' },
  { code: 'CF', en: 'Central African Republic', es: 'República Centroafricana' },
  { code: 'TD', en: 'Chad', es: 'Chad' },
  { code: 'CL', en: 'Chile', es: 'Chile' },
  { code: 'CN', en: 'China', es: 'China' },
  { code: 'CX', en: 'Christmas Island', es: 'Isla de Navidad' },
  { code: 'CC', en: 'Cocos (Keeling) Islands', es: 'Islas Cocos' },
  { code: 'CO', en: 'Colombia', es: 'Colombia' },
  { code: 'KM', en: 'Comoros', es: 'Comoras' },
  { code: 'CG', en: 'Congo', es: 'Congo' },
  { code: 'CD', en: 'Congo (DRC)', es: 'República Democrática del Congo' },
  { code: 'CK', en: 'Cook Islands', es: 'Islas Cook' },
  { code: 'CR', en: 'Costa Rica', es: 'Costa Rica' },
  { code: 'CI', en: "Côte d'Ivoire", es: 'Costa de Marfil' },
  { code: 'HR', en: 'Croatia', es: 'Croacia' },
  { code: 'CU', en: 'Cuba', es: 'Cuba' },
  { code: 'CW', en: 'Curaçao', es: 'Curazao' },
  { code: 'CY', en: 'Cyprus', es: 'Chipre' },
  { code: 'CZ', en: 'Czech Republic', es: 'Chequia' },
  { code: 'DK', en: 'Denmark', es: 'Dinamarca' },
  { code: 'DJ', en: 'Djibouti', es: 'Yibuti' },
  { code: 'DM', en: 'Dominica', es: 'Dominica' },
  { code: 'DO', en: 'Dominican Republic', es: 'República Dominicana' },
  { code: 'EC', en: 'Ecuador', es: 'Ecuador' },
  { code: 'EG', en: 'Egypt', es: 'Egipto' },
  { code: 'SV', en: 'El Salvador', es: 'El Salvador' },
  { code: 'GQ', en: 'Equatorial Guinea', es: 'Guinea Ecuatorial' },
  { code: 'ER', en: 'Eritrea', es: 'Eritrea' },
  { code: 'EE', en: 'Estonia', es: 'Estonia' },
  { code: 'SZ', en: 'Eswatini', es: 'Esuatini' },
  { code: 'ET', en: 'Ethiopia', es: 'Etiopía' },
  { code: 'FK', en: 'Falkland Islands (Malvinas)', es: 'Islas Malvinas' },
  { code: 'FO', en: 'Faroe Islands', es: 'Islas Feroe' },
  { code: 'FJ', en: 'Fiji', es: 'Fiyi' },
  { code: 'FI', en: 'Finland', es: 'Finlandia' },
  { code: 'FR', en: 'France', es: 'Francia' },
  { code: 'GF', en: 'French Guiana', es: 'Guayana Francesa' },
  { code: 'PF', en: 'French Polynesia', es: 'Polinesia Francesa' },
  { code: 'TF', en: 'French Southern Territories', es: 'Territorios Australes Franceses' },
  { code: 'GA', en: 'Gabon', es: 'Gabón' },
  { code: 'GM', en: 'Gambia', es: 'Gambia' },
  { code: 'GE', en: 'Georgia', es: 'Georgia' },
  { code: 'DE', en: 'Germany', es: 'Alemania' },
  { code: 'GH', en: 'Ghana', es: 'Ghana' },
  { code: 'GI', en: 'Gibraltar', es: 'Gibraltar' },
  { code: 'GR', en: 'Greece', es: 'Grecia' },
  { code: 'GL', en: 'Greenland', es: 'Groenlandia' },
  { code: 'GD', en: 'Grenada', es: 'Granada' },
  { code: 'GP', en: 'Guadeloupe', es: 'Guadalupe' },
  { code: 'GU', en: 'Guam', es: 'Guam' },
  { code: 'GT', en: 'Guatemala', es: 'Guatemala' },
  { code: 'GG', en: 'Guernsey', es: 'Guernsey' },
  { code: 'GN', en: 'Guinea', es: 'Guinea' },
  { code: 'GW', en: 'Guinea-Bissau', es: 'Guinea-Bisáu' },
  { code: 'GY', en: 'Guyana', es: 'Guyana' },
  { code: 'HT', en: 'Haiti', es: 'Haití' },
  { code: 'HM', en: 'Heard Island and McDonald Islands', es: 'Islas Heard y McDonald' },
  { code: 'HN', en: 'Honduras', es: 'Honduras' },
  { code: 'HK', en: 'Hong Kong', es: 'Hong Kong' },
  { code: 'HU', en: 'Hungary', es: 'Hungría' },
  { code: 'IS', en: 'Iceland', es: 'Islandia' },
  { code: 'IN', en: 'India', es: 'India' },
  { code: 'ID', en: 'Indonesia', es: 'Indonesia' },
  { code: 'IR', en: 'Iran', es: 'Irán' },
  { code: 'IQ', en: 'Iraq', es: 'Irak' },
  { code: 'IE', en: 'Ireland', es: 'Irlanda' },
  { code: 'IM', en: 'Isle of Man', es: 'Isla de Man' },
  { code: 'IL', en: 'Israel', es: 'Israel' },
  { code: 'IT', en: 'Italy', es: 'Italia' },
  { code: 'JM', en: 'Jamaica', es: 'Jamaica' },
  { code: 'JP', en: 'Japan', es: 'Japón' },
  { code: 'JE', en: 'Jersey', es: 'Jersey' },
  { code: 'JO', en: 'Jordan', es: 'Jordania' },
  { code: 'KZ', en: 'Kazakhstan', es: 'Kazajistán' },
  { code: 'KE', en: 'Kenya', es: 'Kenia' },
  { code: 'KI', en: 'Kiribati', es: 'Kiribati' },
  { code: 'KP', en: 'North Korea', es: 'Corea del Norte' },
  { code: 'KR', en: 'South Korea', es: 'Corea del Sur' },
  { code: 'KW', en: 'Kuwait', es: 'Kuwait' },
  { code: 'KG', en: 'Kyrgyzstan', es: 'Kirguistán' },
  { code: 'LA', en: "Lao People's Democratic Republic", es: 'Laos' },
  { code: 'LV', en: 'Latvia', es: 'Letonia' },
  { code: 'LB', en: 'Lebanon', es: 'Líbano' },
  { code: 'LS', en: 'Lesotho', es: 'Lesoto' },
  { code: 'LR', en: 'Liberia', es: 'Liberia' },
  { code: 'LY', en: 'Libya', es: 'Libia' },
  { code: 'LI', en: 'Liechtenstein', es: 'Liechtenstein' },
  { code: 'LT', en: 'Lithuania', es: 'Lituania' },
  { code: 'LU', en: 'Luxembourg', es: 'Luxemburgo' },
  { code: 'MO', en: 'Macao', es: 'Macao' },
  { code: 'MG', en: 'Madagascar', es: 'Madagascar' },
  { code: 'MW', en: 'Malawi', es: 'Malaui' },
  { code: 'MY', en: 'Malaysia', es: 'Malasia' },
  { code: 'MV', en: 'Maldives', es: 'Maldivas' },
  { code: 'ML', en: 'Mali', es: 'Malí' },
  { code: 'MT', en: 'Malta', es: 'Malta' },
  { code: 'MH', en: 'Marshall Islands', es: 'Islas Marshall' },
  { code: 'MQ', en: 'Martinique', es: 'Martinica' },
  { code: 'MR', en: 'Mauritania', es: 'Mauritania' },
  { code: 'MU', en: 'Mauritius', es: 'Mauricio' },
  { code: 'YT', en: 'Mayotte', es: 'Mayotte' },
  { code: 'MX', en: 'Mexico', es: 'México' },
  { code: 'FM', en: 'Micronesia', es: 'Micronesia' },
  { code: 'MD', en: 'Moldova', es: 'Moldavia' },
  { code: 'MC', en: 'Monaco', es: 'Mónaco' },
  { code: 'MN', en: 'Mongolia', es: 'Mongolia' },
  { code: 'ME', en: 'Montenegro', es: 'Montenegro' },
  { code: 'MS', en: 'Montserrat', es: 'Montserrat' },
  { code: 'MA', en: 'Morocco', es: 'Marruecos' },
  { code: 'MZ', en: 'Mozambique', es: 'Mozambique' },
  { code: 'MM', en: 'Myanmar', es: 'Myanmar' },
  { code: 'NA', en: 'Namibia', es: 'Namibia' },
  { code: 'NR', en: 'Nauru', es: 'Nauru' },
  { code: 'NP', en: 'Nepal', es: 'Nepal' },
  { code: 'NL', en: 'Netherlands', es: 'Países Bajos' },
  { code: 'NC', en: 'New Caledonia', es: 'Nueva Caledonia' },
  { code: 'NZ', en: 'New Zealand', es: 'Nueva Zelanda' },
  { code: 'NI', en: 'Nicaragua', es: 'Nicaragua' },
  { code: 'NE', en: 'Niger', es: 'Níger' },
  { code: 'NG', en: 'Nigeria', es: 'Nigeria' },
  { code: 'NU', en: 'Niue', es: 'Niue' },
  { code: 'NF', en: 'Norfolk Island', es: 'Isla Norfolk' },
  { code: 'MK', en: 'North Macedonia', es: 'Macedonia del Norte' },
  { code: 'MP', en: 'Northern Mariana Islands', es: 'Islas Marianas del Norte' },
  { code: 'NO', en: 'Norway', es: 'Noruega' },
  { code: 'OM', en: 'Oman', es: 'Omán' },
  { code: 'PK', en: 'Pakistan', es: 'Pakistán' },
  { code: 'PW', en: 'Palau', es: 'Palaos' },
  { code: 'PS', en: 'Palestine, State of', es: 'Palestina' },
  { code: 'PA', en: 'Panama', es: 'Panamá' },
  { code: 'PG', en: 'Papua New Guinea', es: 'Papúa Nueva Guinea' },
  { code: 'PY', en: 'Paraguay', es: 'Paraguay' },
  { code: 'PE', en: 'Peru', es: 'Perú' },
  { code: 'PH', en: 'Philippines', es: 'Filipinas' },
  { code: 'PN', en: 'Pitcairn', es: 'Islas Pitcairn' },
  { code: 'PL', en: 'Poland', es: 'Polonia' },
  { code: 'PT', en: 'Portugal', es: 'Portugal' },
  { code: 'PR', en: 'Puerto Rico', es: 'Puerto Rico' },
  { code: 'QA', en: 'Qatar', es: 'Catar' },
  { code: 'RE', en: 'Réunion', es: 'Reunión' },
  { code: 'RO', en: 'Romania', es: 'Rumanía' },
  { code: 'RU', en: 'Russian Federation', es: 'Rusia' },
  { code: 'RW', en: 'Rwanda', es: 'Ruanda' },
  { code: 'BL', en: 'Saint Barthélemy', es: 'San Bartolomé' },
  { code: 'SH', en: 'Saint Helena, Ascension and Tristan da Cunha', es: 'Santa Elena, Ascensión y Tristán de Acuña' },
  { code: 'KN', en: 'Saint Kitts and Nevis', es: 'San Cristóbal y Nieves' },
  { code: 'LC', en: 'Saint Lucia', es: 'Santa Lucía' },
  { code: 'MF', en: 'Saint Martin (French part)', es: 'San Martín (Francia)' },
  { code: 'PM', en: 'Saint Pierre and Miquelon', es: 'San Pedro y Miquelón' },
  { code: 'VC', en: 'Saint Vincent and the Grenadines', es: 'San Vicente y las Granadinas' },
  { code: 'WS', en: 'Samoa', es: 'Samoa' },
  { code: 'SM', en: 'San Marino', es: 'San Marino' },
  { code: 'ST', en: 'Sao Tome and Principe', es: 'Santo Tomé y Príncipe' },
  { code: 'SA', en: 'Saudi Arabia', es: 'Arabia Saudita' },
  { code: 'SN', en: 'Senegal', es: 'Senegal' },
  { code: 'RS', en: 'Serbia', es: 'Serbia' },
  { code: 'SC', en: 'Seychelles', es: 'Seychelles' },
  { code: 'SL', en: 'Sierra Leone', es: 'Sierra Leona' },
  { code: 'SG', en: 'Singapore', es: 'Singapur' },
  { code: 'SX', en: 'Sint Maarten (Dutch part)', es: 'Sint Maarten (Países Bajos)' },
  { code: 'SK', en: 'Slovakia', es: 'Eslovaquia' },
  { code: 'SI', en: 'Slovenia', es: 'Eslovenia' },
  { code: 'SB', en: 'Solomon Islands', es: 'Islas Salomón' },
  { code: 'SO', en: 'Somalia', es: 'Somalia' },
  { code: 'ZA', en: 'South Africa', es: 'Sudáfrica' },
  { code: 'GS', en: 'South Georgia and the South Sandwich Islands', es: 'Georgia del Sur e Islas Sandwich del Sur' },
  { code: 'SS', en: 'South Sudan', es: 'Sudán del Sur' },
  { code: 'ES', en: 'Spain', es: 'España' },
  { code: 'LK', en: 'Sri Lanka', es: 'Sri Lanka' },
  { code: 'SD', en: 'Sudan', es: 'Sudán' },
  { code: 'SR', en: 'Suriname', es: 'Surinam' },
  { code: 'SJ', en: 'Svalbard and Jan Mayen', es: 'Svalbard y Jan Mayen' },
  { code: 'SE', en: 'Sweden', es: 'Suecia' },
  { code: 'CH', en: 'Switzerland', es: 'Suiza' },
  { code: 'SY', en: 'Syrian Arab Republic', es: 'Siria' },
  { code: 'TW', en: 'Taiwan', es: 'Taiwán' },
  { code: 'TJ', en: 'Tajikistan', es: 'Tayikistán' },
  { code: 'TZ', en: 'Tanzania', es: 'Tanzania' },
  { code: 'TH', en: 'Thailand', es: 'Tailandia' },
  { code: 'TL', en: 'Timor-Leste', es: 'Timor Oriental' },
  { code: 'TG', en: 'Togo', es: 'Togo' },
  { code: 'TK', en: 'Tokelau', es: 'Tokelau' },
  { code: 'TO', en: 'Tonga', es: 'Tonga' },
  { code: 'TT', en: 'Trinidad and Tobago', es: 'Trinidad y Tobago' },
  { code: 'TN', en: 'Tunisia', es: 'Túnez' },
  { code: 'TR', en: 'Türkiye', es: 'Türkiye' },
  { code: 'TM', en: 'Turkmenistan', es: 'Turkmenistán' },
  { code: 'TC', en: 'Turks and Caicos Islands', es: 'Islas Turcas y Caicos' },
  { code: 'TV', en: 'Tuvalu', es: 'Tuvalu' },
  { code: 'UG', en: 'Uganda', es: 'Uganda' },
  { code: 'UA', en: 'Ukraine', es: 'Ucrania' },
  { code: 'AE', en: 'United Arab Emirates', es: 'Emiratos Árabes Unidos' },
  { code: 'GB', en: 'United Kingdom', es: 'Reino Unido' },
  { code: 'US', en: 'United States', es: 'Estados Unidos' },
  { code: 'UM', en: 'United States Minor Outlying Islands', es: 'Islas Ultramarinas Menores de EE. UU.' },
  { code: 'UY', en: 'Uruguay', es: 'Uruguay' },
  { code: 'UZ', en: 'Uzbekistan', es: 'Uzbekistán' },
  { code: 'VU', en: 'Vanuatu', es: 'Vanuatu' },
  { code: 'VA', en: 'Vatican City', es: 'Ciudad del Vaticano' },
  { code: 'VE', en: 'Venezuela', es: 'Venezuela' },
  { code: 'VN', en: 'Viet Nam', es: 'Vietnam' },
  { code: 'VG', en: 'Virgin Islands (British)', es: 'Islas Vírgenes Británicas' },
  { code: 'VI', en: 'Virgin Islands (U.S.)', es: 'Islas Vírgenes de EE. UU.' },
  { code: 'WF', en: 'Wallis and Futuna', es: 'Wallis y Futuna' },
  { code: 'EH', en: 'Western Sahara', es: 'Sahara Occidental' },
  { code: 'YE', en: 'Yemen', es: 'Yemen' },
  { code: 'ZM', en: 'Zambia', es: 'Zambia' },
  { code: 'ZW', en: 'Zimbabwe', es: 'Zimbabue' },
];

export const COUNTRIES: Record<string, { en: string; es: string }> = COUNTRY_LIST.reduce((acc, c) => {
  acc[c.code] = { en: c.en, es: c.es };
  return acc;
}, {} as Record<string, { en: string; es: string }>);

export function countryLabel(code: string, lang: 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' = 'en') {
  // For now, FR/DE/IT/PT fall back to EN
  const lookupLang = (lang === 'es') ? 'es' : 'en';
  const name = COUNTRIES[code]?.[lookupLang];
  return name ? `${code} - ${name}` : code;
}
