import React, { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './App';
import { KPIDataProvider } from './context/KPIDataContext';
import { FinanceProvider } from './context/FinanceContext';
import { ThemeProvider } from './hooks/useTheme';
import { HighContrastProvider } from './context/HighContrastContext';
import { SettingsProvider } from './context/SettingsContext';
import { initTelemetry } from './lib/telemetry';
import { QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { createOptimizedQueryClient, setupQueryPersistence, setupBackgroundSync } from './lib/reactQueryOptimizations.v2';
import './styles/index.css';
import './styles/performance.css';
// DISABLED FOR PRODUCTION BETA - all data comes from Firestore now
// import { ensureDemoTenants } from './lib/tenants';
import { ErrorBoundary } from './components/common/ErrorBoundary';
import { OfflineIndicator } from './components/OfflineIndicator';
import { logger } from './lib/logger';
import { initWebVitals, trackResourceTiming, trackLongTasks } from './lib/webVitals';

const el = document.getElementById('root');
if (!el) {
  throw new Error('Root element not found');
}

initTelemetry();
// DISABLED FOR PRODUCTION BETA - all data comes from Firestore now
// try { ensureDemoTenants(); } catch { }

// Initialize Web Vitals monitoring - TEMPORARILY DISABLED TO FIX 405 ERRORS
// initWebVitals();
// trackResourceTiming();
// trackLongTasks();

// Create optimized query client with enhanced caching and performance
const queryClient = createOptimizedQueryClient();

// Setup persistence and background sync
if (typeof window !== 'undefined') {
  setupQueryPersistence(queryClient);
  setupBackgroundSync(queryClient);
}

const AppProviders = ({ children }: { children: React.ReactNode }) => (
  <ErrorBoundary>
    <ThemeProvider>
      <HighContrastProvider>
        <SettingsProvider>
          <QueryClientProvider client={queryClient}>
            <FinanceProvider>
              <KPIDataProvider>
                {children}
                <OfflineIndicator />
                {import.meta.env.DEV && <ReactQueryDevtools initialIsOpen={false} />}
              </KPIDataProvider>
            </FinanceProvider>
          </QueryClientProvider>
        </SettingsProvider>
      </HighContrastProvider>
    </ThemeProvider>
  </ErrorBoundary>
);

const root = createRoot(el);

if (import.meta.env.DEV) {
  root.render(
    <StrictMode>
      <AppProviders>
        <App />
      </AppProviders>
    </StrictMode>
  );
} else {
  root.render(
    <AppProviders>
      <App />
    </AppProviders>
  );
}

// Register Service Worker for PWA - Generated by vite-plugin-pwa
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  window.addEventListener('load', () => {
    // vite-plugin-pwa will inject the SW registration automatically
    // This is just for monitoring and updates
    navigator.serviceWorker.ready.then((registration) => {
      logger.info('Service Worker ready', { scope: registration.scope });

      // Check for updates periodically
      setInterval(() => {
        registration.update();
      }, 60 * 60 * 1000); // Every hour
    });

    // Listen for service worker updates
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      logger.info('Service Worker updated');
      // Optionally show update notification
      // window.location.reload();
    });
  });
}

